/**
 * Build-time prerenderer.
 *
 * GitHub Pages has no server, so "a real URL that returns real HTML" has to be
 * produced at build time. react-dom/server is not an option here: LanguageProvider
 * reads localStorage during render and the sound layer builds an AudioContext, so
 * server rendering would crash and every component would need an SSR audit.
 * Instead we serve the built bundle, render each route in a real headless Chrome,
 * and snapshot the resulting DOM to dist/<route>/index.html.
 *
 * Usage: node scripts/prerender.cjs [--base=/ai-chronicle-2026/]
 */
const http = require('http');
const fs = require('fs');
const path = require('path');
const { chromium } = require('playwright');
const { getSegments } = require('./site_segments.cjs');

const DIST = path.join(__dirname, '..', 'dist');
const PORT = 4321;

const baseArg = process.argv.find((a) => a.startsWith('--base='));
const BASE = baseArg ? baseArg.slice('--base='.length) : '/';

// Derived from ROUTES in src/utils/routes.ts plus every milestone slug in
// src/data/timelineData.ts (see site_segments.cjs).
const SEGMENTS = getSegments();

const ORIGIN = 'https://mumumumuyi.github.io';

// Priority/changefreq tiers keyed by segment shape, matching the hand-written
// sitemap this replaces.
function sitemapEntry(segment, lastmod) {
  const loc = `${ORIGIN}/${segment ? segment + '/' : ''}`;
  const isMilestone = segment.startsWith('milestone/');
  const priority = segment === '' ? '1.0' : segment === 'reader' ? '0.9' : isMilestone ? '0.7' : '0.8';
  const changefreq = segment === '' ? 'daily' : isMilestone ? 'yearly' : 'weekly';
  return `  <url>\n    <loc>${loc}</loc>\n    <lastmod>${lastmod}</lastmod>\n    <changefreq>${changefreq}</changefreq>\n    <priority>${priority}</priority>\n  </url>`;
}

function writeSitemap() {
  const outPath = path.join(DIST, 'sitemap.xml');
  if (BASE !== '/') {
    // The /ai-chronicle-2026/ mirror canonicalises to the root domain and a
    // sitemap may only list URLs at or below its own directory, so the
    // subsite ships no sitemap at all.
    if (fs.existsSync(outPath)) fs.unlinkSync(outPath);
    return;
  }
  const lastmod = new Date().toISOString().slice(0, 10);
  const xml =
    `<?xml version="1.0" encoding="UTF-8"?>\n` +
    `<!-- Generated by scripts/prerender.cjs from site_segments.cjs. Do not edit by hand. -->\n` +
    `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n` +
    SEGMENTS.map((s) => sitemapEntry(s, lastmod)).join('\n') +
    `\n</urlset>\n`;
  fs.writeFileSync(outPath, xml, 'utf8');
  // Keep the tracked copy identical so the next build starts in sync.
  fs.writeFileSync(path.join(__dirname, '..', 'public', 'sitemap.xml'), xml, 'utf8');
}

const MIME = {
  '.html': 'text/html; charset=utf-8',
  '.js': 'text/javascript; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.jpg': 'image/jpeg',
  '.png': 'image/png',
  '.svg': 'image/svg+xml',
  '.txt': 'text/plain; charset=utf-8',
  '.xml': 'application/xml; charset=utf-8',
  '.json': 'application/json; charset=utf-8',
};

function startServer() {
  const server = http.createServer((req, res) => {
    let urlPath = decodeURIComponent(req.url.split('?')[0]);
    if (BASE !== '/' && urlPath.startsWith(BASE)) urlPath = '/' + urlPath.slice(BASE.length);

    let file = path.join(DIST, urlPath);
    if (!fs.existsSync(file) || fs.statSync(file).isDirectory()) {
      // Unknown paths fall back to the SPA shell, the same as a Pages 404 would.
      file = path.join(DIST, 'index.html');
    }
    res.writeHead(200, { 'Content-Type': MIME[path.extname(file)] || 'application/octet-stream' });
    fs.createReadStream(file).pipe(res);
  });
  return new Promise((resolve) => server.listen(PORT, () => resolve(server)));
}

(async () => {
  const server = await startServer();
  const browser = await chromium.launch({ channel: 'chrome' });
  const context = await browser.newContext({ viewport: { width: 1440, height: 900 } });

  // Snapshot the Chinese edition so the crawlable HTML matches <html lang="zh-CN">.
  await context.addInitScript(() => {
    try {
      localStorage.setItem('ai_chronicle_lang', 'zh');
    } catch {
      /* private mode - the app falls back to its own default */
    }
  });

  let failures = 0;

  for (const segment of SEGMENTS) {
    const url = `http://localhost:${PORT}${BASE}${segment ? segment + '/' : ''}`;
    const page = await context.newPage();
    const errors = [];
    page.on('pageerror', (e) => errors.push(e.message));

    // Not networkidle: the AdSense script never settles on a network that
    // blocks it, and the snapshot only needs the app's own DOM to be up.
    await page.goto(url, { waitUntil: 'domcontentloaded', timeout: 60000 });
    await page.waitForFunction(() => {
      const root = document.getElementById('root');
      return !!root && root.children.length > 0;
    }, { timeout: 30000 });
    await page.waitForTimeout(1500);

    const html = await page.evaluate(() => '<!DOCTYPE html>\n' + document.documentElement.outerHTML);
    const textLength = await page.evaluate(() => document.body.innerText.trim().length);
    const title = await page.title();

    const outDir = segment ? path.join(DIST, segment) : DIST;
    fs.mkdirSync(outDir, { recursive: true });
    fs.writeFileSync(path.join(outDir, 'index.html'), html, 'utf8');

    const ok = textLength > 500 && errors.length === 0;
    if (!ok) failures++;
    console.log(
      `[${ok ? 'OK  ' : 'FAIL'}] /${segment || ''}  text=${textLength}  title="${title.slice(0, 40)}"` +
        (errors.length ? `  pageerror=${JSON.stringify(errors.slice(0, 2))}` : '')
    );

    await page.close();
  }

  // GitHub Pages serves 404.html for unknown paths; hand it the SPA shell so a
  // deep link that outlives a rename still boots the app instead of dead-ending.
  fs.copyFileSync(path.join(DIST, 'index.html'), path.join(DIST, '404.html'));

  writeSitemap();

  await browser.close();
  server.close();

  console.log(failures === 0 ? 'PRERENDER_PASS' : `PRERENDER_FAIL=${failures}`);
  process.exit(failures === 0 ? 0 : 1);
})();
